### PR TITLE
Add TypeScript type definitions

### PR DESCRIPTION
**Pull request by luavixen**
I've taken into account all possible code paths when writing these type definitions and due to the way the control flow in some of this library is structured I've had to write some weird types like `Architecture | null | undefined` or `string | null | undefined`. I'm planning to maybe update the way some of these functions are structured to improve readability and give them more consistent return values (preferably all strings all the time) when I have some free time.

### CODE REVIEW

**Comment by luavixen** [comment]
Additionally, what do you think of rewriting your code to use "constructor functions" instead of ES6 classes? It would allow you to remove Babel and reduce bloat in general without changing the API of the library.

**Comment by luavixen** [comment]
Hey! I know TypeScript isn't for everyone, if you aren't alright with the additions I made feel free to close this PR. Also you should fix your switches to include default branches, both getOSVersion and getBrowserVersion can return undefined in v1.0.1.

**Comment by dangeredwolf** [comment]
Sorry aaaa I forgot about your PR! Merging now

**Comment by luavixen** [comment]
Haha, no worries, thanks for merging!

**Comment by dangeredwolf** [comment]
Yeah! Refactoring is fine!

On February 4, 2021 at 6:30 AM, Lua MacDougall <notifications@github.com> wrote:






Haha, no worries! Would you be alright if I did some more light refactoring? Thanks for merging!

**Pull request merged**
